### ISSUE TITLE
pred_3d.py

### ISSUE THREAD

**Issue by qiushenjie** [davidlinhl/medSeg#2]
`468 片满足，当前共 3
469 片满足，当前共 4
正在存盘
470 片满足，当前共 1
volume-4.nii segmentation-4.nii
数据处理中:   4%|▍         | 5/131 [00:17<09:15,  4.41s/it, filename=segmentation-4.nii volume-4.nii]
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`

数据预处理的时候会出现这个问题，内存不足？

**Comment by davidlinhl** [comment]
这个时间有点长了细节记不太请，可以跑的时候打开任务管理器看一下，你这个扫描看起来很大

**Comment by qiushenjie** [comment]
重启后暂时解决了，应该就是内存不足，要加内存条...

**Comment by davidlinhl** [comment]
方便提供一些这个爆内存扫描的基本信息吗，主要是分辨率，层数和每个像素多少位。我这可以考虑下一版尝试解决一下这个问题

**Comment by qiushenjie** [comment]
# 开始切片
if cfg.PREP.PLANE == "xy":
    for frame in range(1, volume.shape[2] - 1):
        if label[:, :, frame].sum() > cfg.PREP.THRESH:
            # vol = volume[:, :, frame - thick : frame + thick + 1]
            vol = volume[:, :, frame]
除了这里我改动一下，其他的没动。分辨率是[512, 512, 1]，batch是16，像素的话还是volume:float16，label:int8

**Comment by davidlinhl** [comment]
这里应该是需要把整个扫描先读进来，整个扫描有多少片

**Comment by qiushenjie** [comment]
......现在已经看不到报错信息的, 之前是.nii大于400M的时候就会中断, 比如volume-4.nii. 大概率是我电脑的问题

**Comment by davidlinhl** [comment]
好的，研究一下如何根据内存决定分部分读取数据，谢谢
